name = "RNNLibrary"
uuid = "7da795eb-0c01-4a9f-92fa-f037859c1cd3"
authors = ["Kacper Karaś <karas.kacper@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
